###################
## Laurie        ##
###################
- id: https://doi.org/10.1038/s41551-024-01282-8
  tags: 
  - highlights
  - Antibodies
  - Eukaryotic cell lines
  - Animals and other organisms
  - Flow cytometry
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41551-024-01282-8/MediaObjects/41551_2024_1282_Fig1_HTML.png
  
- id: https://doi.org/10.1038/s43018-023-00570-7
  tags:
  - Cancer
  - Imaging the immune system
  - Immunotherapy 
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43018-023-00570-7/MediaObjects/43018_2023_570_Fig2_HTML.png
  
- id: doi:10.1016/j.xpro.2022.101922
  tags:
  - highlights
  - genomics
  - tb 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166722008024-fx1_lrg.jpg
  
- id: https://doi.org/10.1136/jitc-2022-004807
  tags:
  - single cell
  - transcriptomics 
  image: https://jitc.bmj.com/content/jitc/10/8/e004807/F1.medium.gif
  
- id: doi:10.1016/j.cell.2022.02.021
  tags:
  - single cell
  - transcriptomics 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S009286742200201X-fx1_lrg.jpg

- id: https://doi.org/10.1126/sciimmunol.abe8219
  tags:
  - highlights
  - single cell
  - transcriptomics 
  image: https://www.science.org/cms/asset/5f2ec23e-aac6-4643-b154-40bed2014a74/keyimage.gif

- id: doi:10.1016/bs.mie.2019.05.048

- id: https://doi.org/10.1158/0008-5472.CAN-15-3352
  image: https://aacrjournals.org/view-large/figure/13294761/2087fig1.jpeg

- id: https://doi.org/10.1016/j.molonc.2015.10.008

- id: https://doi.org/10.1182/blood-2015-08-664755
  image: https://ashpublications.org/view-large/figure/7494804/2781f1.jpeg
  
- id: doi:10.1016/j.cytogfr.2013.05.001

- id: doi:10.4161/onci.23082

- id: doi:10.1126/scitranslmed.3003807
  
###################
## Chloe         ##
###################
- id: doi:10.1126/science.adl6173
  tags:
  - Cancer immunology
  image: https://www.science.org/cms/10.1126/science.adl6173/asset/7ca7cafe-1830-4624-b400-39f821fb66f8/assets/images/large/science.adl6173-fa.jpg

- id: doi:10.1038/s41586-020-2746-2
  tags:
  - Cancer models
  - Epistasis
  - Immune evasion
  - Tumour heterogeneity
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41586-020-2746-2/MediaObjects/41586_2020_2746_Fig1_HTML.png
  
###################
## Chuang        ##
###################
- id: 10.1182/blood-2024-209815
  tags:
  - Gene expression analysis
  - DLBCL

- id: doi:10.3389/fimmu.2024.1505971
  tags:
  - Gene expression analysis
  - B cell biology
  - Monoclonal antibody cloning
  image: https://www.frontiersin.org/files/Articles/1505971/fimmu-15-1505971-HTML/image_m/fimmu-15-1505971-g001.jpg

- id: doi:10.3389/fimmu.2020.00216 
  tags:
  - B Cell Biology
  image: https://raw.githubusercontent.com/Chuang1118/FB5P-seq/refs/heads/master/LOGOn.png

- id: doi:10.1016/j.jhep.2020.05.053
  tags:
  - Autoreactive T-cell
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168827820304530-fx1_lrg.jpg

- id: doi:10.1038/s41590-020-0731-4
  tags:
  - Confocal microscopy
  - Gene expression analysis
  - Plasmacytoid dendritic cells
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41590-020-0731-4/MediaObjects/41590_2020_731_Fig3_HTML.png

- id: doi:10.1126/sciimmunol.abg3570
  tags:
  - Gene expression analysis
  - Conventional type 1 dendritic cells
  image: https://www.science.org/cms/asset/834bd1b5-0b4f-4b2c-908b-42676a4a9f3d/sciimmunol.2021.6.issue-61.largecover.jpg

- id: doi:10.1016/j.immuni.2022.06.002
  tags:
  - Gene expression analysis
  - Lung
  - Memory B cells
  - SARS-CoV-2
  - Influenza virus
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1074761322002400-fx1_lrg.jpg
  
- id: doi:10.1101/2022.04.06.487285
  tags:
  - Gene expression analysis
  - Follicular lymphoma

- id: doi:10.1101/2024.03.26.586770
  tags:
  - Gene expression analysis
  - Autoimmune liver diseases

- id: doi:10.1101/2024.07.26.605240
  tags:
  - Gene expression analysis
  - B cell biology

- id: doi:10.1182/blood-2021-147246
  tags:
  - Gene expression analysis
  - Spatial transcriptomics
  - T-cell lymphoma
  image: https://ashpublications.org/view-large/figure/10284193/2393fig01.png
