###################
## Laurie        ##
###################
- id: https://doi.org/10.1038/s41551-024-01282-8
  tags: 
  - highlights
  - Antibodies
  - Eukaryotic cell lines
  - Animals and other organisms
  - Flow cytometry
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41551-024-01282-8/MediaObjects/41551_2024_1282_Fig1_HTML.png
  
- id: https://doi.org/10.1038/s43018-023-00570-7
  tags:
  - Cancer
  - Imaging the immune system
  - Immunotherapy 
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43018-023-00570-7/MediaObjects/43018_2023_570_Fig2_HTML.png
  
- id: doi:10.1016/j.xpro.2022.101922
  tags:
  - highlights
  - genomics
  - tb 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166722008024-fx1_lrg.jpg
  
- id: https://doi.org/10.1136/jitc-2022-004807
  tags:
  - single cell
  - transcriptomics 
  image: https://jitc.bmj.com/content/jitc/10/8/e004807/F1.medium.gif
  
- id: doi:10.1016/j.cell.2022.02.021
  tags:
  - single cell
  - transcriptomics 
  image: https://ars.els-cdn.com/content/image/1-s2.0-S009286742200201X-fx1_lrg.jpg

- id: https://doi.org/10.1126/sciimmunol.abe8219
  tags:
  - highlights
  - single cell
  - transcriptomics 
  image: https://www.science.org/cms/asset/5f2ec23e-aac6-4643-b154-40bed2014a74/keyimage.gif

- id: doi:10.1016/bs.mie.2019.05.048

- id: https://doi.org/10.1158/0008-5472.CAN-15-3352
  image: https://aacrjournals.org/view-large/figure/13294761/2087fig1.jpeg

- id: https://doi.org/10.1016/j.molonc.2015.10.008

- id: https://doi.org/10.1182/blood-2015-08-664755
  image: https://ashpublications.org/view-large/figure/7494804/2781f1.jpeg
  
- id: doi:10.1016/j.cytogfr.2013.05.001

- id: doi:10.4161/onci.23082

- id: doi:10.1126/scitranslmed.3003807
